chore: updated a single translation
graasp/graasp-app-rewards pull request #24
Opened 2019-01-24 15:46 UTC by jashpam

Change on the button name to delete a medal.

closes #23

2019-01-24 15:49 UTC, juancarlosfarah requested changes
You changed a translation file, but also the lock file has changed. I think it's because your `yarn` is old.

2019-01-26 09:02 UTC, juancarlosfarah commented
@jashpam, thanks for that. I had to do some wrestling with this to get it to work. I will go ahead and merge it to `develop`. You can go back to `develop` and pull to have the latest changes.

2019-01-26 09:03 UTC, juancarlosfarah approved these changes

2019-01-26 09:03 UTC, merged

2019-01-27 12:09 UTC, jashpam commented
many thanks!