chore: updating UI
graasp/graasp-app-rewards pull request #26
Opened 2019-01-30 22:29 UTC by jashpam

Small changes on the UI, plus translations to Spanish.

closes #25

2019-01-31 12:46 UTC, juancarlosfarah requested changes
Excellent commit! 👏 

Just some minor changes. Please see below.

2019-01-31 12:46 UTC, juancarlosfarah commented on data/default.json
> +      "id": "5c055c1083d22e0211h24ad1",
Good catch!

2019-01-31 12:46 UTC, juancarlosfarah commented on src/components/modes/student/StudentView.js
> +        { t(' ') }
Why don't you just remove this line @jashpam ?

2019-01-31 12:46 UTC, juancarlosfarah commented on src/components/modes/teacher/AssignBadgeForm.js
> +import './AssignedBadges.css';
Here you should create a new CSS file and call it `AssignBadgeForm.css` containing the rules necessary for this file.

2019-01-31 12:46 UTC, juancarlosfarah commented on src/components/modes/teacher/AssignBadgeForm.js
> +          className="AssignMedal"
I would use `AssignBadge` as the class name, so that it is aligned with the rest of the nomenclature.

2019-01-31 12:46 UTC, juancarlosfarah commented on src/langs/es.json
> +    "No badges have been assigned to you yet": "Ninguna medalla se te ha sido asignada aun",
aún

2019-02-13 09:08 UTC, juancarlosfarah commented
@jashpam, were you able to have a look at the changes I requested?

2019-02-13 13:26 UTC, jashpam commented
> @jashpam, were you able to have a look at the changes I requested?

Hey @juancarlosfarah, sorry that I have been a bit busy lately. Will work on the changes you asked this weekend ;)

2019-02-16 14:50 UTC, juancarlosfarah approved these changes

2019-02-16 14:50 UTC, merged